name: PyPi Upload

on: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run Tox
        run: |
          tox -e build

      - name: Store Dist
        uses: actions/upload-artifact@v2.2.4
        with:
          name: dist
          path: dist/

  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install twine
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Retreive Dist
        uses: actions/download-artifact@v2.0.10
        with:
          name: dist

      - name: Upload package to PyPi
        run: |
          twine upload -u "__token__" -p "${{ secrets.PYPI_TOKEN }}" dist/*
